/**
 *********************************************************************
 * Licensed Materials - Property of IBM
 * Restricted Materials of IBM
 * 5900-A1Y
 *
 * © Copyright IBM Corp. 2020 All Rights Reserved.
 *
 * US Government Users Restricted Rights - Use, duplication or
 * disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
 *********************************************************************
*/

/**
 * NOTE: This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

// @ts-ignore
import { RequestFile } from '../api';

export interface GoodbyeResponseAllOf {
    /**
    * message
    */
    'message'?: GoodbyeResponseAllOf.MessageEnum;
}

export class GoodbyeResponseAllOfImpl implements GoodbyeResponseAllOf {
    'message'?: GoodbyeResponseAllOf.MessageEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "message",
            "baseName": "message",
            "type": "GoodbyeResponseAllOf.MessageEnum"
        }    ];

    static getAttributeTypeMap() {
        return GoodbyeResponseAllOfImpl.attributeTypeMap;
    }
}

export namespace GoodbyeResponseAllOf {
    export enum MessageEnum {
        Bye = 'bye',
        Goodbye = 'goodbye'
    }
}
