/**
 *********************************************************************
 * Licensed Materials - Property of IBM
 * Restricted Materials of IBM
 * 5900-A1Y
 *
 * © Copyright IBM Corp. 2020 All Rights Reserved.
 *
 * US Government Users Restricted Rights - Use, duplication or
 * disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
 *********************************************************************
*/

/**
 * NOTE: This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

// @ts-ignore
import { RequestFile } from '../api';
// @ts-ignore
import {
    // @ts-ignore
    GoodbyeResponseAllOf,
    // @ts-ignore
    GoodbyeResponseAllOfImpl,
} from './goodbyeResponseAllOf';
// @ts-ignore
import {
    // @ts-ignore
    Response,
    // @ts-ignore
    ResponseImpl,
} from './response';

export interface GoodbyeResponse extends Response {
    /**
    * message
    */
    'message'?: GoodbyeResponse.MessageEnum;
}

export class GoodbyeResponseImpl extends ResponseImpl implements GoodbyeResponse {
    'message'?: GoodbyeResponse.MessageEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "message",
            "baseName": "message",
            "type": "GoodbyeResponse.MessageEnum"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(GoodbyeResponseImpl.attributeTypeMap);
    }
}

export namespace GoodbyeResponse {
    export enum MessageEnum {
        Bye = 'bye',
        Goodbye = 'goodbye'
    }
}
