/**
 *********************************************************************
 * Licensed Materials - Property of IBM
 * Restricted Materials of IBM
 * 5900-A1Y
 *
 * © Copyright IBM Corp. 2020 All Rights Reserved.
 *
 * US Government Users Restricted Rights - Use, duplication or
 * disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
 *********************************************************************
*/

/**
 * NOTE: This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

// @ts-ignore
import { RequestFile } from '../api';
// @ts-ignore
import {
    // @ts-ignore
    HelloResponseAllOf,
    // @ts-ignore
    HelloResponseAllOfImpl,
} from './helloResponseAllOf';
// @ts-ignore
import {
    // @ts-ignore
    Response,
    // @ts-ignore
    ResponseImpl,
} from './response';

export interface HelloResponse extends Response {
    /**
    * message
    */
    'message'?: HelloResponse.MessageEnum;
}

export class HelloResponseImpl extends ResponseImpl implements HelloResponse {
    'message'?: HelloResponse.MessageEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "message",
            "baseName": "message",
            "type": "HelloResponse.MessageEnum"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(HelloResponseImpl.attributeTypeMap);
    }
}

export namespace HelloResponse {
    export enum MessageEnum {
        Hi = 'hi',
        Hello = 'hello'
    }
}
