/**
 *********************************************************************
 * Licensed Materials - Property of IBM
 * Restricted Materials of IBM
 * 5900-A1Y
 *
 * © Copyright IBM Corp. 2020 All Rights Reserved.
 *
 * US Government Users Restricted Rights - Use, duplication or
 * disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
 *********************************************************************
*/

/**
 * NOTE: This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

// @ts-ignore
import { RequestFile } from '../api';

export interface HelloRequest {
    /**
    * use nickname
    */
    'useNickname': boolean;
    /**
    * are you sure
    */
    'reallyUseNickname'?: HelloRequest.ReallyUseNicknameEnum;
    /**
    * nickname
    */
    'nickname'?: string;
    'repeat'?: number;
}

export class HelloRequestImpl implements HelloRequest {
    'useNickname': boolean;
    'reallyUseNickname'?: HelloRequest.ReallyUseNicknameEnum;
    'nickname'?: string;
    'repeat'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "useNickname",
            "baseName": "use_nickname",
            "type": "boolean"
        },
        {
            "name": "reallyUseNickname",
            "baseName": "really_use_nickname",
            "type": "HelloRequest.ReallyUseNicknameEnum"
        },
        {
            "name": "nickname",
            "baseName": "nickname",
            "type": "string"
        },
        {
            "name": "repeat",
            "baseName": "repeat",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return HelloRequestImpl.attributeTypeMap;
    }
}

export namespace HelloRequest {
    export enum ReallyUseNicknameEnum {
        Yes = 'yes',
        No = 'no'
    }
}
