/**
 *********************************************************************
 * Licensed Materials - Property of IBM
 * Restricted Materials of IBM
 * 5900-A1Y
 *
 * © Copyright IBM Corp. 2020 All Rights Reserved.
 *
 * US Government Users Restricted Rights - Use, duplication or
 * disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
 *********************************************************************
*/

/**
 * NOTE: This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

// This is the entrypoint for the package
import { readFileSync } from 'fs';
import { join } from 'path';

const apiSpec = JSON.parse(
  readFileSync(join(__dirname, './openapi.json'), 'utf-8')
);

export const openApiSpec = apiSpec;
export * from './api/apis';
export * from './model/models';
